<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.open</groupId>
    <artifactId>open-parent</artifactId>
    <version>${revision}</version>
    <packaging>pom</packaging>

    <modules>
        <module>commons</module>
        <module>extends</module>
        <module>starters</module>
    </modules>

    <properties>
        <revision>1.8-SNAPSHOT</revision>
        <java.version>1.8</java.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <spring-boot.version>2.5.15</spring-boot.version>
        <spring-cloud.version>2020.0.6</spring-cloud.version>
        <spring-cloud-alibaba.version>2.2.9.RELEASE</spring-cloud-alibaba.version>
        <hutool.version>5.8.30</hutool.version>
        <sa-token.version>1.44.0</sa-token.version>

        <okhttp.version>4.12.0</okhttp.version>
        <mybatis-plus.version>3.5.7</mybatis-plus.version>
        <dynamic-datasource.version>4.3.1</dynamic-datasource.version>
        <mapstruct-plus.version>1.4.8</mapstruct-plus.version>
        <redisson.version>3.46.0</redisson.version>
        <lock4j-redisson.version>2.2.7</lock4j-redisson.version>
        <fastexcel.version>1.2.0</fastexcel.version>
        <ip2region.version>2.7.0</ip2region.version>
        <bouncycastle.version>1.81</bouncycastle.version>
        <aws-sdk.version>2.31.78</aws-sdk.version>
        <justauth.version>1.16.7</justauth.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>${spring-boot.version}</version>
                <scope>import</scope>
                <type>pom</type>
            </dependency>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>${spring-cloud.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>com.alibaba.cloud</groupId>
                <artifactId>spring-cloud-alibaba-dependencies</artifactId>
                <version>${spring-cloud-alibaba.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>cn.hutool</groupId>
                <artifactId>hutool-bom</artifactId>
                <version>${hutool.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>cn.dev33</groupId>
                <artifactId>sa-token-bom</artifactId>
                <version>${sa-token.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>com.squareup.okhttp3</groupId>
                <artifactId>okhttp</artifactId>
                <version>${okhttp.version}</version>
            </dependency>
            <dependency>
                <groupId>org.jetbrains.kotlin</groupId>
                <artifactId>kotlin-stdlib</artifactId>
                <version>1.9.25</version>
            </dependency>
            <dependency>
                <groupId>com.baomidou</groupId>
                <artifactId>mybatis-plus-boot-starter</artifactId>
                <version>${mybatis-plus.version}</version>
            </dependency>
            <dependency>
                <groupId>com.baomidou</groupId>
                <artifactId>dynamic-datasource-spring-boot-starter</artifactId>
                <version>${dynamic-datasource.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.linpeilie</groupId>
                <artifactId>mapstruct-plus-spring-boot-starter</artifactId>
                <version>${mapstruct-plus.version}</version>
            </dependency>
            <dependency>
                <groupId>org.redisson</groupId>
                <artifactId>redisson-spring-boot-starter</artifactId>
                <version>${redisson.version}</version>
            </dependency>
            <dependency>
                <groupId>com.baomidou</groupId>
                <artifactId>lock4j-redisson-spring-boot-starter</artifactId>
                <version>${lock4j-redisson.version}</version>
            </dependency>
            <dependency>
                <groupId>cn.idev.excel</groupId>
                <artifactId>fastexcel</artifactId>
                <version>${fastexcel.version}</version>
            </dependency>
            <!-- 离线IP地址定位库 -->
            <dependency>
                <groupId>org.lionsoul</groupId>
                <artifactId>ip2region</artifactId>
                <version>${ip2region.version}</version>
            </dependency>
            <dependency>
                <groupId>org.bouncycastle</groupId>
                <artifactId>bcprov-jdk15to18</artifactId>
                <version>${bouncycastle.version}</version>
            </dependency>
            <dependency>
                <groupId>software.amazon.awssdk</groupId>
                <artifactId>s3</artifactId>
                <version>${aws-sdk.version}</version>
            </dependency>
            <dependency>
                <groupId>software.amazon.awssdk</groupId>
                <artifactId>netty-nio-client</artifactId>
                <version>${aws-sdk.version}</version>
            </dependency>
            <dependency>
                <groupId>software.amazon.awssdk</groupId>
                <artifactId>s3-transfer-manager</artifactId>
                <version>${aws-sdk.version}</version>
            </dependency>
            <dependency>
                <groupId>me.zhyd.oauth</groupId>
                <artifactId>JustAuth</artifactId>
                <version>${justauth.version}</version>
            </dependency>

            <!--    open dependencis begin    -->
            <dependency>
                <groupId>com.open</groupId>
                <artifactId>open-commons</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.open</groupId>
                <artifactId>open-extend-i18n</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.open</groupId>
                <artifactId>open-extend-manager</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.open</groupId>
                <artifactId>open-starter-cache</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.open</groupId>
                <artifactId>open-starter-excel</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.open</groupId>
                <artifactId>open-starter-http</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.open</groupId>
                <artifactId>open-starter-json</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.open</groupId>
                <artifactId>open-starter-oss</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.open</groupId>
                <artifactId>open-starter-satoken</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.open</groupId>
                <artifactId>open-starter-security</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.open</groupId>
                <artifactId>open-starter-social</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.open</groupId>
                <artifactId>open-starter-sse</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.open</groupId>
                <artifactId>open-starter-swarm-bots</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.open</groupId>
                <artifactId>open-starter-mybatis-plus</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.open</groupId>
                <artifactId>open-starter-tenant</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.open</groupId>
                <artifactId>open-starter-web</artifactId>
                <version>${revision}</version>
            </dependency>
            <!--    open dependencis end    -->
        </dependencies>
    </dependencyManagement>

    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.codehaus.mojo</groupId>
                    <artifactId>flatten-maven-plugin</artifactId>
                    <version>1.7.0</version>
                    <executions>
                        <execution>
                            <id>flatten</id>
                            <phase>process-resources</phase>
                            <goals>
                                <goal>flatten</goal>
                            </goals>
                        </execution>
                        <execution>
                            <id>flatten-clean</id>
                            <phase>pre-clean</phase>
                            <goals>
                                <goal>clean</goal>
                            </goals>
                        </execution>
                    </executions>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>3.14.0</version>
                    <configuration>
                        <source>${java.version}</source>
                        <target>${java.version}</target>
                        <encoding>${project.build.sourceEncoding}</encoding>
                        <annotationProcessorPaths>
                            <path>
                                <groupId>org.projectlombok</groupId>
                                <artifactId>lombok</artifactId>
                            </path>
                            <path>
                                <groupId>io.github.linpeilie</groupId>
                                <artifactId>mapstruct-plus-processor</artifactId>
                                <version>${mapstruct-plus.version}</version>
                            </path>
                            <path>
                                <groupId>org.projectlombok</groupId>
                                <artifactId>lombok-mapstruct-binding</artifactId>
                                <version>0.2.0</version>
                            </path>
                            <path>
                                <groupId>org.springframework.boot</groupId>
                                <artifactId>spring-boot-configuration-processor</artifactId>
                                <version>${spring-boot.version}</version>
                            </path>
                        </annotationProcessorPaths>
                    </configuration>
                </plugin>
            </plugins>
        </pluginManagement>
        <plugins>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>flatten-maven-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
            </plugin>
        </plugins>
    </build>

    <distributionManagement>
        <repository>
            <id>github-proton6980</id>
            <url>https://maven.pkg.github.com/proton6980/packages</url>
        </repository>
        <snapshotRepository>
            <id>github-proton6980</id>
            <url>https://maven.pkg.github.com/proton6980/packages</url>
        </snapshotRepository>
    </distributionManagement>

</project>