<?xml version="1.0" encoding="UTF-8" ?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.open</groupId>
        <artifactId>open-extends</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>open-extend-manager</artifactId>
    <packaging>jar</packaging>

    <dependencies>
        <dependency>
            <groupId>com.open</groupId>
            <artifactId>open-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>com.open</groupId>
            <artifactId>open-starter-tenant</artifactId>
        </dependency>
        <dependency>
            <groupId>com.open</groupId>
            <artifactId>open-starter-cache</artifactId>
        </dependency>
        <dependency>
            <groupId>com.open</groupId>
            <artifactId>open-starter-excel</artifactId>
        </dependency>
        <dependency>
            <groupId>com.open</groupId>
            <artifactId>open-starter-sse</artifactId>
        </dependency>
        <dependency>
            <groupId>com.open</groupId>
            <artifactId>open-starter-oss</artifactId>
        </dependency>
        <dependency>
            <groupId>com.open</groupId>
            <artifactId>open-starter-social</artifactId>
        </dependency>

        <!--  自动生成YML配置关联JSON文件  -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-configuration-processor</artifactId>
        </dependency>
    </dependencies>
</project>