<?xml version="1.0" encoding="UTF-8" ?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.open</groupId>
        <artifactId>open-starters</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>open-starter-sse</artifactId>
    <packaging>jar</packaging>

    <dependencies>
        <dependency>
            <groupId>com.open</groupId>
            <artifactId>open-commons</artifactId>
            <version>${revision}</version>
        </dependency>
        <dependency>
            <groupId>com.open</groupId>
            <artifactId>open-starter-json</artifactId>
            <version>${revision}</version>
        </dependency>
        <dependency>
            <groupId>com.open</groupId>
            <artifactId>open-starter-cache</artifactId>
            <version>${revision}</version>
        </dependency>
        <dependency>
            <groupId>com.open</groupId>
            <artifactId>open-starter-satoken</artifactId>
            <version>${revision}</version>
        </dependency>
        <dependency>
            <groupId>com.open</groupId>
            <artifactId>open-starter-web</artifactId>
            <version>${revision}</version>
        </dependency>
    </dependencies>
</project>